import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const workflowPath = path.join(root, '.github', 'workflows', 'control-plane-ci.yml')
const packageJson = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8')) as {
  scripts?: Record<string, string>
}
const scripts = packageJson.scripts || {}
const testCiScript = scripts['test:ci'] || ''

assert.ok(existsSync(workflowPath), 'control-plane CI workflow must exist')

const workflow = readFileSync(workflowPath, 'utf8')
const secretScanner = readFileSync(path.join(root, 'scripts', 'secret-scan.cjs'), 'utf8')
const packageDesktop = readFileSync(path.join(root, 'scripts', 'package-desktop.cjs'), 'utf8')
const electronE2eSmoke = readFileSync(path.join(root, 'scripts', 'smoke-electron-e2e.ts'), 'utf8')

assert.match(workflow, /name:\s*Control Plane CI/, 'workflow must have a stable production-hardening name')
assert.match(workflow, /push:/, 'workflow must run on pushes')
assert.match(workflow, /pull_request:/, 'workflow must run on pull requests')
assert.match(workflow, /workflow_dispatch:/, 'workflow must support manual release-candidate runs')
assert.match(workflow, /public_release/, 'workflow must expose a manual public-release signing gate')
assert.match(workflow, /refs\/tags\/v/, 'workflow must require signing for version-tag release validation')
assert.match(workflow, /runs-on:\s*windows-latest/, 'workflow must exercise the Windows desktop packaging environment')
assert.match(workflow, /actions\/checkout@v4/, 'workflow must check out the repository')
assert.match(workflow, /actions\/setup-node@v4/, 'workflow must set up Node')
assert.match(workflow, /node-version:\s*'24'/, 'workflow must use the supported Node 24 release line')
assert.match(workflow, /\bnpm ci\b/, 'workflow must install locked dependencies with npm ci')
assert.match(workflow, /\bnpm run audit:dependencies\b/, 'workflow must audit production dependencies')
assert.match(workflow, /\bnpm run secret:scan\b/, 'workflow must scan tracked files for checked-in secrets')
assert.match(workflow, /\bnpm run lint\b/, 'workflow must lint source before semantic checks')
assert.match(workflow, /\bnpm run typecheck\b/, 'workflow must run semantic type-checking')
assert.match(workflow, /\bnpm test\b/, 'workflow must run the hardening smoke suite')
assert.match(workflow, /\bnpm run build:server\b/, 'workflow must build the backend bundle')
assert.match(workflow, /\bnpm run build:client\b/, 'workflow must build the frontend bundle')
assert.match(workflow, /\bnpm run smoke:electron-e2e\b/, 'workflow must exercise packaged Electron startup and shutdown')
assert.match(workflow, /\bnpm run prepare:runtime-bundles\b/, 'workflow must prepare reproducible runtime bundles before release evidence')
assert.match(workflow, /\bnpm run prepare:openclaw-vendor\b/, 'workflow must prepare vendored OpenClaw dependencies before packaging')
assert.match(workflow, /node scripts\/package-desktop\.cjs --dir/, 'workflow must package the desktop directory before release evidence')
assert.match(workflow, /\bnpm run smoke:packaged-electron-launch\b/, 'workflow must launch the packaged desktop output before release evidence')
assert.match(workflow, /\bnpm run release:evidence\b/, 'workflow must generate release SBOM and checksum evidence')
assert.match(workflow, /DYSTOPAI_RELEASE_SIGNING_ENABLED/, 'workflow must make release signing an explicit opt-in')
assert.match(workflow, /DYSTOPAI_RELEASE_REQUIRE_SIGNING/, 'workflow must make public-release signing mandatory when requested')
assert.match(workflow, /DYSTOPAI_RELEASE_SIGNING_PRIVATE_KEY_PEM/, 'workflow must read release signing private key from a GitHub secret')
assert.match(workflow, /\bnpm run release:sign\b/, 'workflow must sign release evidence when release signing is enabled')
assert.match(workflow, /\bnpm run release:validate\b/, 'workflow must validate release artifacts before upload')
assert.match(workflow, /release\/evidence\/dystopai-sbom\.cdx\.json/, 'workflow must verify the generated SBOM')
assert.match(workflow, /release\/evidence\/checksums\.sha256/, 'workflow must verify the checksum manifest')
assert.match(workflow, /release\/evidence\/release-evidence\.json/, 'workflow must verify the evidence summary')
assert.match(workflow, /release\/evidence\/distribution-signing\.json/, 'workflow must require distribution signing evidence for public release runs')
assert.match(workflow, /actions\/upload-artifact@v4/, 'workflow must upload release evidence')
assert.match(workflow, /if-no-files-found:\s*error/, 'workflow must fail when release evidence is missing')
assert.match(workflow, /permissions:\s*\n\s*contents:\s*read/, 'workflow must use read-only repository permissions')

const typecheckIndex = workflow.indexOf('npm run typecheck')
const auditIndex = workflow.indexOf('npm run audit:dependencies')
const secretScanIndex = workflow.indexOf('npm run secret:scan')
const lintIndex = workflow.indexOf('npm run lint')
const testIndex = workflow.indexOf('npm test')
const serverBuildIndex = workflow.indexOf('npm run build:server')
const clientBuildIndex = workflow.indexOf('npm run build:client')
const electronE2eIndex = workflow.indexOf('npm run smoke:electron-e2e')
const runtimeIndex = workflow.indexOf('npm run prepare:runtime-bundles')
const openClawVendorIndex = workflow.indexOf('npm run prepare:openclaw-vendor')
const packageIndex = workflow.indexOf('node scripts/package-desktop.cjs --dir')
const packagedLaunchIndex = workflow.indexOf('npm run smoke:packaged-electron-launch')
const evidenceIndex = workflow.indexOf('npm run release:evidence')
const signingIndex = workflow.indexOf('npm run release:sign')
const validationIndex = workflow.indexOf('npm run release:validate')
const uploadIndex = workflow.indexOf('actions/upload-artifact@v4')
const testCiTypecheckIndex = testCiScript.indexOf('npm run typecheck')
const testCiOpenClawIndex = testCiScript.indexOf('npm run smoke:openclaw')
const testCiCiWorkflowIndex = testCiScript.indexOf('npm run smoke:ci-workflow')

assert.ok(auditIndex >= 0 && auditIndex < secretScanIndex, 'workflow must audit dependencies before local secret scanning')
assert.ok(secretScanIndex < lintIndex, 'workflow must run secret scanning before local source linting')
assert.ok(lintIndex < typecheckIndex, 'workflow must lint before semantic type-checking')
assert.ok(typecheckIndex < testIndex, 'workflow must type-check before running the full smoke suite')
assert.ok(testIndex < serverBuildIndex, 'workflow must run tests before producing build artifacts')
assert.ok(serverBuildIndex < clientBuildIndex, 'workflow must build the server before the client evidence step')
assert.ok(clientBuildIndex < electronE2eIndex, 'workflow must build client output before Electron E2E')
assert.ok(electronE2eIndex < runtimeIndex, 'workflow must run Electron E2E before preparing release evidence inputs')
assert.ok(runtimeIndex < packageIndex, 'workflow must prepare runtime metadata before packaging the desktop directory')
assert.ok(runtimeIndex < openClawVendorIndex, 'workflow must prepare runtime metadata before vendored OpenClaw dependencies')
assert.ok(openClawVendorIndex < packageIndex, 'workflow must prepare vendored OpenClaw dependencies before packaging the desktop directory')
assert.ok(packageIndex < packagedLaunchIndex, 'workflow must package the desktop directory before launching packaged output')
assert.ok(packagedLaunchIndex < evidenceIndex, 'workflow must launch packaged output before generating release evidence')
assert.ok(evidenceIndex < signingIndex, 'workflow must generate release evidence before signing it')
assert.ok(signingIndex < validationIndex, 'workflow must sign release evidence before final validation')
assert.ok(validationIndex < uploadIndex, 'workflow must validate release artifacts before uploading evidence')
assert.ok(evidenceIndex < validationIndex, 'workflow must validate evidence only after it is generated')

assert.match(scripts['smoke:ci-workflow'] || '', /tsx scripts\/smoke-ci-workflow\.ts/, 'package scripts must expose CI workflow smoke coverage')
assert.match(scripts['audit:dependencies'] || '', /npm audit --omit=dev --audit-level=high/, 'package scripts must expose a production dependency audit gate')
assert.match(scripts['secret:scan'] || '', /node scripts\/secret-scan\.cjs/, 'package scripts must expose checked-in secret scanning')
assert.match(scripts['lint'] || '', /eslint \./, 'package scripts must expose source linting')
assert.match(scripts['release:validate'] || '', /node scripts\/validate-release-artifacts\.cjs/, 'package scripts must expose release artifact validation')
assert.match(scripts['prepare:openclaw-vendor'] || '', /node scripts\/prepare-openclaw-vendor\.cjs/, 'package scripts must expose vendored OpenClaw dependency preparation')
assert.match(scripts['smoke:electron-e2e'] || '', /tsx scripts\/smoke-electron-e2e\.ts/, 'package scripts must expose Electron E2E smoke coverage')
assert.match(scripts['smoke:packaged-electron-launch'] || '', /tsx scripts\/smoke-packaged-electron-launch\.ts/, 'package scripts must expose packaged Electron launch smoke coverage')
assert.match(electronE2eSmoke, /function ensureElectronBinary/, 'Electron E2E smoke must explicitly ensure the Electron binary before import')
assert.match(electronE2eSmoke, /require\.resolve\('electron\/package\.json'\)/, 'Electron E2E smoke must resolve the Electron package without importing electron first')
assert.match(electronE2eSmoke, /writeFileSync\(pathFile, platformPath\)/, 'Electron E2E smoke must restore path.txt when Actions checkout/install misses it')
assert.match(packageDesktop, /prepare-openclaw-vendor\.cjs/, 'desktop packaging must prepare vendored OpenClaw dependencies when invoked directly')
assert.match(scripts['smoke:openclaw'] || '', /smoke-openclaw-contracts\.mjs/, 'package scripts must expose OpenClaw contract smoke coverage')
assert.match(testCiScript, /npm run lint && npm run typecheck/, 'test:ci must lint before type-checking')
assert.match(testCiScript, /npm run smoke:openclaw/, 'test:ci must include OpenClaw contract smoke coverage')
assert.match(testCiScript, /npm run smoke:ci-workflow/, 'test:ci must include CI workflow smoke coverage')
assert.match(testCiScript, /npm run secret:scan/, 'test:ci must include checked-in secret scanning')
assert.match(testCiScript, /npm run smoke:release-validation/, 'test:ci must include release validation smoke coverage')
assert.ok(testCiTypecheckIndex >= 0 && testCiTypecheckIndex < testCiOpenClawIndex, 'test:ci must type-check before OpenClaw contract smoke coverage')
assert.ok(testCiOpenClawIndex >= 0 && testCiOpenClawIndex < testCiCiWorkflowIndex, 'test:ci must run OpenClaw contract smoke before final CI workflow contract checks')

assert.match(secretScanner, /git', \['ls-files', '-z', '--cached', '--others', '--exclude-standard'\]/, 'secret scan must inspect tracked and untracked non-ignored repository files')
assert.match(secretScanner, /private-key/, 'secret scan must detect private key material')
assert.match(secretScanner, /openai-api-key/, 'secret scan must detect OpenAI-style API keys')
assert.match(secretScanner, /github-token/, 'secret scan must detect GitHub tokens')
assert.match(secretScanner, /aws-access-key-id/, 'secret scan must detect AWS access key IDs')
assert.match(secretScanner, /allowlist\\s\+secret/, 'secret scan must support explicit allowlist markers')

console.log('ci workflow contract ok')
