import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const NEXUS_STORE_MAX_LINES = 3_889
const NEXUS_STORE_MAX_API_REQUEST_CALLS = 0
const NEXUS_STORE_MAX_API_PATH_LINES = 0

function readWorkspaceFile(relativePath: string): string {
  return readFileSync(path.join(root, relativePath), 'utf8')
}

const store = readWorkspaceFile('src/store/nexusStore.ts')
const apiClient = readWorkspaceFile('src/api/client.ts')
const partyApi = readWorkspaceFile('src/api/party.ts')
const agentTurnsApi = readWorkspaceFile('src/api/agentTurns.ts')
const missionsApi = readWorkspaceFile('src/api/missions.ts')
const providerAuthApi = readWorkspaceFile('src/api/providerAuth.ts')
const pluginsApi = readWorkspaceFile('src/api/plugins.ts')
const pluginsPanel = readWorkspaceFile('src/components/plugins/PluginsPanel.tsx')
const agentResponseConsole = readWorkspaceFile('src/components/monitor/AgentResponseConsole.tsx')
const nexusUiState = readWorkspaceFile('src/store/nexusUiState.ts')
const runtimeProjectionState = readWorkspaceFile('src/store/runtimeProjectionState.ts')
const commandConsoleState = readWorkspaceFile('src/store/commandConsoleState.ts')
const agentConfigState = readWorkspaceFile('src/store/agentConfigState.ts')
const missionState = readWorkspaceFile('src/store/missionState.ts')
const nexusPersistence = readWorkspaceFile('src/store/nexusPersistence.ts')
const stateSplitTest = readWorkspaceFile('tests/nexusStoreStateSplit.test.ts')
const packageJson = JSON.parse(readWorkspaceFile('package.json')) as { scripts?: Record<string, string> }
const lines = store.split(/\r?\n/)
const apiRequestCallLines = lines.filter((line) => /\bapiRequest(?:<|\s*\()/.test(line))
const apiPathLines = lines.filter((line) => /['"`]\/api\//.test(line))
const directFetchMatches = [...store.matchAll(/\bfetch\s*\(/g)]

assert.ok(
  lines.length <= NEXUS_STORE_MAX_LINES,
  `src/store/nexusStore.ts grew past the Phase H item 76 budget: ${lines.length}/${NEXUS_STORE_MAX_LINES} lines. Move API calls or projection state into src/api/* or focused renderer services before adding store code.`,
)
assert.ok(
  apiRequestCallLines.length <= NEXUS_STORE_MAX_API_REQUEST_CALLS,
  `src/store/nexusStore.ts added API request calls: ${apiRequestCallLines.length}/${NEXUS_STORE_MAX_API_REQUEST_CALLS}. Move new backend calls into src/api/* modules first.`,
)
assert.ok(
  apiPathLines.length <= NEXUS_STORE_MAX_API_PATH_LINES,
  `src/store/nexusStore.ts added API path literals: ${apiPathLines.length}/${NEXUS_STORE_MAX_API_PATH_LINES}. Move new backend endpoints into src/api/* modules first.`,
)
assert.equal(directFetchMatches.length, 0, `nexusStore should not own direct fetch calls after Phase H item 79, found ${directFetchMatches.length}`)
assert.match(apiClient, /export async function apiRequest/, 'renderer API client should remain the JSON request boundary')
assert.match(partyApi, /export function fetchPartyOverview/, 'party API module should own party overview requests')
assert.match(partyApi, /apiRequest<PartyOverviewPayload>\('\/api\/party\/overview'/, 'party overview endpoint should live in src/api/party.ts')
assert.match(partyApi, /export function saveAgentConfig/, 'party API module should own agent config saves')
assert.match(partyApi, /apiRequest<AgentConfigSavePayload>\(`\/api\/party\/agent\/\$\{encodeURIComponent\(agentId\)\}\/config`/, 'agent config endpoint should live in src/api/party.ts')
assert.match(partyApi, /export function recruitPartyAgent/, 'party API module should own recruit requests')
assert.match(partyApi, /apiRequest<RecruitAgentPayload>\('\/api\/party\/recruit'/, 'recruit endpoint should live in src/api/party.ts')
assert.match(partyApi, /export function saveAgentResource/, 'party API module should own agent resource saves')
assert.match(partyApi, /apiRequest<AgentResourceSavePayload>\(`\/api\/party\/resources\/\$\{encodeURIComponent\(agentId\)\}\/\$\{encodeURIComponent\(file\)\}`/, 'agent resource endpoint should live in src/api/party.ts')
assert.match(partyApi, /export function retirePartyAgent/, 'party API module should own retire requests')
assert.match(agentTurnsApi, /export function preflightAgentRuntime/, 'agent-turn API module should own runtime preflight requests')
assert.match(agentTurnsApi, /apiRequest<AgentRuntimePreflightPayload>\('\/api\/openclaw\/agent-preflight'/, 'agent preflight endpoint should live in src/api/agentTurns.ts')
assert.match(agentTurnsApi, /export function sendBufferedAgentTurn/, 'agent-turn API module should own buffered turn requests')
assert.match(agentTurnsApi, /apiRequest<AgentTurnPayload>\('\/api\/openclaw\/agent-turn'/, 'buffered agent-turn endpoint should live in src/api/agentTurns.ts')
assert.match(agentTurnsApi, /export async function sendStreamingAgentTurn/, 'agent-turn API module should own streaming turn requests')
assert.match(agentTurnsApi, /fetch\(apiUrl\('\/api\/openclaw\/agent-turn\/stream'\)/, 'agent-turn stream endpoint should live in src/api/agentTurns.ts')
assert.match(agentTurnsApi, /createSseFrameParser\(\)/, 'agent-turn API module should own SSE frame iteration')
assert.match(agentTurnsApi, /contentType\.includes\('text\/event-stream'\)/, 'agent-turn API module should require event-stream responses before frame parsing')
assert.match(agentTurnsApi, /export function clearAgentTurnSessions/, 'agent-turn API module should own session clear requests')
assert.match(agentTurnsApi, /apiRequest<AgentTurnSessionClearPayload>\('\/api\/openclaw\/agent-turn\/sessions\/clear'/, 'session clear endpoint should live in src/api/agentTurns.ts')
assert.match(missionsApi, /export function fetchMissionProjection/, 'mission API module should own mission projection requests')
assert.match(missionsApi, /apiRequest<BackendMissionsPayload>\('\/api\/missions\/projection'/, 'mission projection endpoint should live in src/api/missions.ts')
assert.match(missionsApi, /export function startMission/, 'mission API module should own mission start requests')
assert.match(missionsApi, /apiRequest<MissionStartPayload>\('\/api\/missions\/start'/, 'mission start endpoint should live in src/api/missions.ts')
assert.match(missionsApi, /export function stopMission/, 'mission API module should own mission stop requests')
assert.match(missionsApi, /apiRequest\('\/api\/missions\/stop'/, 'mission stop endpoint should live in src/api/missions.ts')
assert.match(providerAuthApi, /export function fetchProviderAuthStatuses/, 'provider auth API module should own provider auth status requests')
assert.match(providerAuthApi, /apiRequest<ProviderAuthStatusesPayload>\(options\.refresh \? '\/api\/auth\/providers\?refresh=1' : '\/api\/auth\/providers'/, 'provider auth status endpoints should live in src/api/providerAuth.ts')
assert.match(providerAuthApi, /export function saveProviderApiKey/, 'provider auth API module should own API-key saves')
assert.match(providerAuthApi, /apiRequest\(`\/api\/auth\/providers\/\$\{encodeURIComponent\(provider\)\}`/, 'provider API-key endpoint should live in src/api/providerAuth.ts')
assert.match(providerAuthApi, /export function startProviderOAuthSession/, 'provider auth API module should own OAuth starts')
assert.match(providerAuthApi, /export function fetchProviderOAuthSession/, 'provider auth API module should own OAuth polling')
assert.match(providerAuthApi, /export function submitProviderOAuthManual/, 'provider auth API module should own manual OAuth completion')
assert.match(pluginsApi, /export function fetchPlugins/, 'plugin API module should own plugin list requests')
assert.match(pluginsApi, /options\.force \? '\/api\/plugins\?refresh=1' : '\/api\/plugins'/, 'plugin list endpoints should live in src/api/plugins.ts')
assert.match(pluginsApi, /export function runOpenClawPluginCommand/, 'plugin API module should own OpenClaw command requests used by the plugin panel')
assert.match(pluginsApi, /pluginApiData<PluginApiPayload>\(\s*'\/api\/openclaw\/command'/, 'OpenClaw command endpoint should live in src/api/plugins.ts')
assert.match(pluginsApi, /export function setupClawTalkPlugin/, 'plugin API module should own ClawTalk setup requests')
assert.match(pluginsApi, /'\/api\/plugins\/clawtalk\/setup'/, 'ClawTalk setup endpoint should live in src/api/plugins.ts')
assert.match(pluginsApi, /export function savePluginSetup/, 'plugin API module should own direct plugin config saves')
assert.match(pluginsApi, /`\/api\/plugins\/\$\{encodeURIComponent\(pluginId\)\}\/config`/, 'plugin config endpoint should live in src/api/plugins.ts')
assert.match(pluginsApi, /export function searchOpenClawPlugins/, 'plugin API module should own plugin search requests')
assert.match(pluginsApi, /export function installOpenClawPlugin/, 'plugin API module should own plugin install requests')
assert.match(pluginsApi, /export function setPluginEnabled/, 'plugin API module should own plugin enable-disable requests')
assert.match(pluginsApi, /export function updateOpenClawPlugin/, 'plugin API module should own single-plugin update requests')
assert.match(pluginsApi, /export function updateAllOpenClawPlugins/, 'plugin API module should own update-all requests')
assert.match(pluginsApi, /export function inspectOpenClawPluginRuntime/, 'plugin API module should own plugin runtime inspect requests')
assert.match(pluginsApi, /export function restartPluginGateway/, 'plugin API module should own plugin Gateway restart requests')
assert.match(pluginsApi, /export function uninstallOpenClawPlugin/, 'plugin API module should own plugin uninstall requests')
assert.match(pluginsPanel, /from '..\/..\/api\/plugins'/, 'PluginsPanel should consume plugin API helpers')
assert.doesNotMatch(pluginsPanel, /from '..\/..\/api\/client'/, 'PluginsPanel should not import the JSON API client directly')
assert.doesNotMatch(pluginsPanel, /['"`]\/api\/(?:plugins|openclaw\/command)/, 'plugin endpoint literals should stay out of PluginsPanel after Phase H item 81')
assert.doesNotMatch(pluginsPanel, /\bapiRequest(?:<|\s*\()/, 'PluginsPanel should not own JSON API request calls after Phase H item 81')
assert.match(store, /from '..\/api\/party'/, 'nexusStore should consume party API helpers')
assert.match(store, /from '..\/api\/agentTurns'/, 'nexusStore should consume agent-turn API helpers')
assert.match(store, /from '..\/api\/missions'/, 'nexusStore should consume mission API helpers')
assert.match(store, /from '\.\/nexusUiState'/, 'nexusStore should consume UI-only state helpers from src/store/nexusUiState.ts')
assert.match(store, /from '\.\/runtimeProjectionState'/, 'nexusStore should consume runtime projection state helpers from src/store/runtimeProjectionState.ts')
assert.match(store, /from '\.\/commandConsoleState'/, 'nexusStore should consume command-console state helpers from src/store/commandConsoleState.ts')
assert.match(store, /from '\.\/agentConfigState'/, 'nexusStore should consume agent config state helpers from src/store/agentConfigState.ts')
assert.match(store, /from '\.\/missionState'/, 'nexusStore should consume mission state helpers from src/store/missionState.ts')
assert.match(store, /from '\.\/nexusPersistence'/, 'nexusStore should consume persistence helpers from src/store/nexusPersistence.ts')
assert.match(
  store,
  /interface NexusState extends NexusAgentConfigState, NexusMissionState, NexusUiState, NexusRuntimeProjectionState, NexusCommandConsoleResponseState, NexusCoordinationState/,
  'nexusStore should compose agent config, mission, UI-only, runtime projection, command-console response, and coordination state interfaces explicitly',
)
assert.doesNotMatch(store, /interface NexusPersistedState/, 'nexusStore should not keep agent config and mission fields in one persisted interface after Phase H item 83')
assert.match(store, /makeAgentConfigState\(\)/, 'nexusStore initial state should compose agent config state through the agent config module')
assert.match(store, /makeNexusUiState\(agents\)/, 'nexusStore initial state should compose UI-only state through the UI state module')
assert.match(store, /makeMissionState\(\)/, 'nexusStore initial state should compose mission persistence state through the mission state module')
assert.match(store, /makeRuntimeProjectionState\(agents\)/, 'nexusStore initial state should compose volatile runtime projection through the runtime projection module')
assert.match(store, /makeCommandConsoleResponseState\(\)/, 'nexusStore initial state should compose command-console response state through the command-console state module')
assert.match(store, /merge: mergeNexusPersistedState/, 'nexusStore persistence merge should delegate to the persistence module')
assert.match(store, /partialize: partializeNexusPersistedState/, 'nexusStore partialize should delegate to the persistence module')
assert.match(store, /removeCommandConsoleDraftsForAgent\(normalized\)/, 'nexusStore should delegate retired-agent draft cleanup to commandConsoleState')
assert.doesNotMatch(store, /automnia:command-draft:/, 'command draft storage keys should stay out of nexusStore after Phase H item 84')
assert.match(store, /createControlStreamProjector\(\)/, 'nexusStore should keep stream projection state separate from transport')
assert.match(store, /sendStreamingAgentTurn\(/, 'nexusStore should delegate agent-turn streaming transport to src/api/agentTurns.ts')
assert.match(store, /onStreamComplete: streamProjector\.complete/, 'nexusStore should finalize stream projection through the API helper callback')
assert.match(store, /await fetchMissionProjection\(\)/, 'nexusStore should sync mission projection through the mission API module')
assert.match(store, /requestMissionStart\(\{/, 'nexusStore should launch missions through the mission API module')
assert.match(store, /requestMissionStop\(current\.id\)/, 'nexusStore should stop missions through the mission API module')
assert.doesNotMatch(store, /apiRequest(?:<|\s*\()/, 'nexusStore should not own JSON API request calls after Phase H item 79')
assert.doesNotMatch(store, /['"`]\/api\//, 'all API path literals should stay out of nexusStore after Phase H item 79')
assert.doesNotMatch(store, /export type AppTab =/, 'AppTab should live in src/store/nexusUiState.ts after Phase H item 82')
assert.match(nexusUiState, /export interface NexusUiState/, 'UI state module should own the UI-only state shape')
assert.match(nexusUiState, /export function normalizeNexusSelection/, 'UI state module should own selection normalization')
assert.match(nexusUiState, /export function makeNexusUiState/, 'UI state module should own UI initial state construction')
assert.doesNotMatch(nexusUiState, /\bactiveMission\b|\bagentResponses\b|\boperationStates\b/, 'UI state module should not own runtime projection fields')
assert.match(runtimeProjectionState, /export interface NexusRuntimeProjectionState/, 'runtime projection module should own the volatile runtime projection shape')
assert.match(runtimeProjectionState, /export function makeRuntimeProjectionState/, 'runtime projection module should own runtime projection initial state construction')
assert.match(runtimeProjectionState, /export function preserveRuntimeProjectionState/, 'runtime projection module should own persistence-merge runtime projection behavior')
assert.match(runtimeProjectionState, /export function updateAgentConfigSaveStatus/, 'runtime projection module should own runtime save status projection updates')
assert.doesNotMatch(runtimeProjectionState, /\bagentResponses\b|\bbusyAgentIds\b/, 'runtime projection module should not own command-console response state after Phase H item 84')
assert.doesNotMatch(runtimeProjectionState, /\bselectedAgentId\b|\bisEditorOpen\b|\btab:/, 'runtime projection module should not own UI-only fields')
assert.match(commandConsoleState, /export interface NexusCommandConsoleResponseState/, 'command-console state module should own response and busy-lane state shape')
assert.match(commandConsoleState, /export type CommandConsoleDraft/, 'command-console state module should own draft state shape')
assert.match(commandConsoleState, /export function makeCommandConsoleDraftStorageKey/, 'command-console state module should own draft storage keys')
assert.match(commandConsoleState, /export function readCommandConsoleDraft/, 'command-console state module should own draft reads')
assert.match(commandConsoleState, /export function writeCommandConsoleDraft/, 'command-console state module should own draft writes')
assert.match(commandConsoleState, /export function removeCommandConsoleDraftsForAgent/, 'command-console state module should own retired-agent draft cleanup')
assert.match(commandConsoleState, /export function makeCommandConsoleResponseState/, 'command-console state module should own command-console response initial state')
assert.match(commandConsoleState, /export function preserveCommandConsoleResponseState/, 'command-console state module should own command-console response merge behavior')
assert.match(commandConsoleState, /export function createQueuedCommandConsoleResponse/, 'command-console state module should own queued response projection')
assert.match(commandConsoleState, /export function applyQueuedCommandConsoleResponsePatch/, 'command-console state module should own queued response duration patching')
assert.doesNotMatch(commandConsoleState, /\bactiveMission\b|\bmissionFeed\b|\boperationStates\b|\bselectedAgentId\b/, 'command-console state module should not own mission, runtime-operation, or UI-only fields')
assert.match(agentResponseConsole, /from '..\/..\/store\/commandConsoleState'/, 'AgentResponseConsole should consume command-console draft helpers')
assert.doesNotMatch(agentResponseConsole, /\blocalStorage\b/, 'AgentResponseConsole should not own command draft localStorage access after Phase H item 84')
assert.doesNotMatch(agentResponseConsole, /type CommandConsoleDraft =/, 'AgentResponseConsole should not own command draft state shape after Phase H item 84')
assert.match(agentConfigState, /export interface NexusAgentConfigState/, 'agent config state module should own the roster and party state shape')
assert.match(agentConfigState, /export function makeAgentConfigState/, 'agent config state module should own agent config initial state construction')
assert.match(agentConfigState, /export function mergeAgentConfigState/, 'agent config state module should own agent config hydration')
assert.match(agentConfigState, /export function partializeAgentConfigState/, 'agent config state module should own agent config partialization')
assert.match(agentConfigState, /export function sanitizePartyIds/, 'agent config state module should own party containment and dedupe')
assert.match(agentConfigState, /export function sanitizeAgentForPersistentStore/, 'agent config state module should own persisted agent sanitization')
assert.doesNotMatch(agentConfigState, /\bmissionDraft\b|\bmissionHistory\b|\bmissionReports\b/, 'agent config state module should not own mission fields')
assert.match(missionState, /export interface NexusMissionState/, 'mission state module should own mission persistence shape')
assert.match(missionState, /export function makeMissionState/, 'mission state module should own mission initial state construction')
assert.match(missionState, /export function mergeMissionState/, 'mission state module should own mission hydration')
assert.match(missionState, /export function partializeMissionState/, 'mission state module should own mission partialization')
assert.doesNotMatch(missionState, /\bagents\b|\bactivePartyIds\b|\bconfirmedPartyIds\b|\bretiredAgentIds\b/, 'mission state module should not own agent config fields')
assert.match(nexusPersistence, /export const NEXUS_STORAGE_KEY = 'nexus-v10'/, 'persistence module should own the nexus-v10 storage key')
assert.match(nexusPersistence, /export const NEXUS_PERSISTED_VERSION = 5/, 'persistence module should own the current persisted payload version')
assert.match(nexusPersistence, /export const MIN_NEXUS_PERSISTED_VERSION = 3/, 'persistence module should own the minimum accepted payload version')
assert.match(nexusPersistence, /export function mergeNexusPersistedState/, 'persistence module should own persisted-state migration')
assert.match(nexusPersistence, /data\._version < MIN_NEXUS_PERSISTED_VERSION/, 'persistence module should reject stale persisted payload versions')
assert.match(nexusPersistence, /mergeAgentConfigState\(data\)/, 'persistence module should hydrate agent config through the agent config module')
assert.match(nexusPersistence, /mergeMissionState\(data, current\)/, 'persistence module should hydrate mission state through the mission module')
assert.match(nexusPersistence, /preserveRuntimeProjectionState\(current\)/, 'persistence module should keep runtime projection volatile during hydration')
assert.match(nexusPersistence, /preserveCommandConsoleResponseState\(current\)/, 'persistence module should keep command-console responses volatile during hydration')
assert.match(nexusPersistence, /export function partializeNexusPersistedState/, 'persistence module should own persisted payload partialization')
assert.match(nexusPersistence, /partializeAgentConfigState\(state\)/, 'persistence module should persist agent config through the agent config module')
assert.match(nexusPersistence, /partializeMissionState\(state\)/, 'persistence module should persist mission state through the mission module')
assert.match(stateSplitTest, /makeNexusUiState/, 'unit coverage should exercise UI-only state construction')
assert.match(stateSplitTest, /makeRuntimeProjectionState/, 'unit coverage should exercise runtime projection state construction')
assert.match(stateSplitTest, /preserveRuntimeProjectionState/, 'unit coverage should exercise volatile runtime projection merge behavior')
assert.match(stateSplitTest, /makeCommandConsoleResponseState/, 'unit coverage should exercise command-console response state construction')
assert.match(stateSplitTest, /readCommandConsoleDraft/, 'unit coverage should exercise command-console draft storage')
assert.match(stateSplitTest, /createQueuedCommandConsoleResponse/, 'unit coverage should exercise queued command-console response projection')
assert.match(stateSplitTest, /makeAgentConfigState/, 'unit coverage should exercise agent config state construction')
assert.match(stateSplitTest, /mergeAgentConfigState/, 'unit coverage should exercise agent config hydration')
assert.match(stateSplitTest, /makeMissionState/, 'unit coverage should exercise mission state construction')
assert.match(stateSplitTest, /mergeMissionState/, 'unit coverage should exercise mission state hydration')
assert.match(stateSplitTest, /mergeNexusPersistedState/, 'unit coverage should exercise nexus-v10 persisted-state migration')
assert.match(stateSplitTest, /partializeNexusPersistedState/, 'unit coverage should exercise nexus-v10 persisted payload partialization')
assert.match(stateSplitTest, /MIN_NEXUS_PERSISTED_VERSION/, 'unit coverage should pin stale persisted-state rejection')
assert.match(stateSplitTest, /NEXUS_PERSISTED_VERSION/, 'unit coverage should pin the current persisted payload version')
assert.equal(
  packageJson.scripts?.['smoke:renderer-store-boundary'],
  'tsx scripts/smoke-renderer-store-boundary.ts',
  'package.json should expose smoke:renderer-store-boundary',
)
assert.ok(
  packageJson.scripts?.['test:ci']?.includes('npm run smoke:renderer-store-boundary'),
  'test:ci should run the renderer store boundary smoke',
)

console.log(
  `renderer store boundary ok (${lines.length}/${NEXUS_STORE_MAX_LINES} nexusStore lines, ${apiRequestCallLines.length}/${NEXUS_STORE_MAX_API_REQUEST_CALLS} apiRequest calls, ${apiPathLines.length}/${NEXUS_STORE_MAX_API_PATH_LINES} API path literals, ${directFetchMatches.length} direct fetches)`,
)
